services:
    autologin:
       class: Auto\AutologinBundle\Service\AutologinHelper
       arguments:          
          entityManager: "@doctrine.orm.entity_manager"
          container: "@service_container"
          router: "@router"
#    auto_autologin.example:
#        class: Auto\AutologinBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
