services:
    urlhelper:
       class: Sopinet\AutologinBundle\Service\UrlHelper
       arguments:
          container: "@service_container"
#    auto_autologin.example:
#        class: Sopinet\AutologinBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
