services:
    urlhelper:
       class: Sopinet\AutologinBundle\Service\UrlHelper
       arguments:
          container: "@service_container"
    sopinet.autologin.extension:
        class: Sopinet\AutologinBundle\Twig\AutologinExtension
        arguments: ["@urlhelper"]
        tags:
            - { name: twig.extension }
#    auto_autologin.example:
#        class: Sopinet\AutologinBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
